<?php

/*
Makes a new calendar. It needs the name of the calendar, and user's ID.
It returns the following object:

{
    id: <number>
}
*/

require 'database_connection.php';
require 'utility.php';

$name = $_GET['name'];
$user_id = $_GET['user_id'];

// This will store the final result
$json_result = array();

// Insert a new record in the Calendar table:
$query = "
INSERT INTO Calendar (Name, Uid)
VALUES ('$name', '$user_id')";

$result = mysqli_query($link, $query);
if ($result === FALSE) {
    printf("query could not be executed.\n");
    exit(1);
} else {
    // printf("query successfully executed.\n");
}

// This is the ID which was generated by the previous query:
$id = mysqli_insert_id($link);

$json_result['id'] = $id;
output_json($json_result);

?>
