<?php

/*
Makes a new event. Also adds records to the Attends and Contains tables.
It returns the following object:

{
    id: <event id>
}
*/

require 'database_connection.php';
require 'utility.php';

$name = $_GET['name'];
$start_time = $_GET['start_time'];
$duration = $_GET['duration'];
$room_no = $_GET['room_no'];
$user_id = $_GET['user_id'];
$cal_id = $_GET['cal_id'];

// This will store the final result
$json_result = array();

// This contains all the sql queries:
$queries = [];

// Insert a new record in the Event table:
array_push($queries, "
INSERT INTO Event (Name, StartTime, Duration, RoomNo)
VALUES ('$name', '$start_time', '$duration', '$room_no')");

// Loop through all queries in $queries, and run them:
$num_queries = count($queries);
for ($i = 0; $i < $num_queries; $i++) {
    if (mysqli_query($link, $queries[$i]) === FALSE) {
        printf("query %d failed.\n", $i);
        exit(1);
    }
}

// This is the ID which was generated by the previous query:
$id = mysqli_insert_id($link);

$json_result['id'] = $id;
output_json($json_result);

?>
