<?php

/*
Makes a new event. Also adds records to the Attends and Contains tables.
It returns the following object:

{
    id: <event id>
}
*/

require 'database_connection.php';
require 'utility.php';

$name = $_GET['name'];
$start_time = $_GET['start_time'];
$duration = $_GET['duration'];
$room_no = $_GET['room_no'];
$user_id = $_GET['user_id'];
$cal_id = $_GET['cal_id'];

// This will store the final result
$json_result = array();

// This contains all the sql queries:
$queries = [];

// Insert a new record in the Event table:
$new_event_query = "
INSERT INTO Event (Name, StartTime, Duration, RoomNo, Uid)
VALUES ('$name', '$start_time', '$duration', '$room_no', '$user_id')";

$result = mysqli_query($link, $new_event_query);
if ($result === FALSE) {
    printf("query could not be executed.\n");
    exit(1);
}

// This is the ID which was generated by the previous query:
$event_id = mysqli_insert_id($link);

// Insert a new record in the Contains table:
$new_contains_query = "
INSERT INTO Contains (Cid, Eid)
VALUES ('$cal_id', '$event_id')";

$result = mysqli_query($link, $new_contains_query);
if ($result === FALSE) {
    printf("query could not be executed.\n");
    exit(1);
}

// Insert a new record in the Attends table:
$new_contains_query = "
INSERT INTO Attends (Uid, Eid)
VALUES ('$user_id', '$event_id')";

$result = mysqli_query($link, $new_contains_query);
if ($result === FALSE) {
    printf("query could not be executed.\n");
    exit(1);
}

$json_result['id'] = $event_id;
output_json($json_result);

?>
