<?php

/*
Makes a new reminder.
It returns the following object:

{
    id: <reminder id>
}
*/

require 'database_connection.php';
require 'utility.php';

$user_id = $_GET['user_id'];
$type = $_GET['type'];
$time = $_GET['time'];
$event_id = $_GET['event_id'];

// This will store the final result
$json_result = array();

// This contains all the sql queries:
$queries = [];

// Insert a new record in the Event table:
$new_event_query = "
INSERT INTO Reminder (Uid, Type, Time, Eid)
VALUES ('$user_id', '$type', '$time', '$event_id')";

$result = mysqli_query($link, $new_event_query);
if ($result === FALSE) {
    printf("query could not be executed.\n");
    exit(1);
}

// This is the ID which was generated by the previous query:
$reminder_id = mysqli_insert_id($link);

$json_result['id'] = $reminder_id;
output_json($json_result);

?>
