<?php

/*
Makes a new user account. It only needs the name of the user.
It returns the following object:

{
    id: <number>
}
*/

require 'database_connection.php';
require 'utility.php';

$name = $_GET['name'];

// This will store the final result
$json_result = array();

// Insert a new record in the User table:
$query = "
INSERT INTO User (User.Name)
VALUES ('$name')";

$result = mysqli_query($link, $query);
if ($result === FALSE) {
    printf("query could not be executed.\n");
    exit(1);
} else {
    // printf("query successfully executed.\n");
}

// This is the ID which was generated by the previous query:
$id = mysqli_insert_id($link);

$json_result['id'] = $id;
output_json($json_result);

?>
